on:
push:
branches: [ "main" ]

jobs:
demo:
runs-on:ubuntu-latest

steps:
-name:Checkoutrepository
uses:actions/checkout@v4

-name:Accesssecretvalue
run:echo"The secret key is ${{ secrets.MY_SECRET_KEY }}"
